### ISSUE TITLE
Error generating token 生成失败

### ISSUE THREAD

**Issue by yayaQAQ** [Ink-Osier/GenerateArkose#1]
我按照ninja的文档下载了对应的har文件，docker也走了代理，但是生成失败是为什么呢？
<img width="1199" alt="image" src="https://github.com/Ink-Osier/GenerateArkose/assets/20497531/bb8ccb88-d5ba-4455-a80b-20d264753a65">

**Comment by Ink-Osier** [comment]
> 我按照ninja的文档下载了对应的har文件，docker也走了代理，但是生成失败是为什么呢？ <img alt="image" width="1199" src="https://private-user-images.githubusercontent.com/20497531/297250128-bb8ccb88-d5ba-4455-a80b-20d264753a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjIwMTMsIm5iZiI6MTcwNTQ2MTcxMywicGF0aCI6Ii8yMDQ5NzUzMS8yOTcyNTAxMjgtYmI4Y2NiODgtZDViYS00NDU1LWE4MGItMjBkMjY0NzUzYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMjE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZGI1NTU4N2E0ZWNmNmJkNDU3OTNiNGE0M2QyYTI4MzViMWZmYzI0Nzc1ZWZlMTU5NDIwOTE3NTU0MzYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SEHfsUHqrn2I65OKVD091WFogHA-9oZtzwmTuolTRcI">

你的代理可以正常打开ChatGPT的网页么

**Comment by yayaQAQ** [comment]
> > 我按照ninja的文档下载了对应的har文件，docker也走了代理，但是生成失败是为什么呢？ <img alt="image" width="1199" src="https://private-user-images.githubusercontent.com/20497531/297250128-bb8ccb88-d5ba-4455-a80b-20d264753a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjIwMTMsIm5iZiI6MTcwNTQ2MTcxMywicGF0aCI6Ii8yMDQ5NzUzMS8yOTcyNTAxMjgtYmI4Y2NiODgtZDViYS00NDU1LWE4MGItMjBkMjY0NzUzYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMjE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZGI1NTU4N2E0ZWNmNmJkNDU3OTNiNGE0M2QyYTI4MzViMWZmYzI0Nzc1ZWZlMTU5NDIwOTE3NTU0MzYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SEHfsUHqrn2I65OKVD091WFogHA-9oZtzwmTuolTRcI">
> 
> 你的代理可以正常打开ChatGPT的网页么

你好，是可以的，也就是说你是正常用的对吧？如果你是正常用的话，我就去找一个国外的服务器试试。

**Comment by Ink-Osier** [comment]
> > > 我按照ninja的文档下载了对应的har文件，docker也走了代理，但是生成失败是为什么呢？ <img alt="image" width="1199" src="https://private-user-images.githubusercontent.com/20497531/297250128-bb8ccb88-d5ba-4455-a80b-20d264753a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjIwMTMsIm5iZiI6MTcwNTQ2MTcxMywicGF0aCI6Ii8yMDQ5NzUzMS8yOTcyNTAxMjgtYmI4Y2NiODgtZDViYS00NDU1LWE4MGItMjBkMjY0NzUzYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMjE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZGI1NTU4N2E0ZWNmNmJkNDU3OTNiNGE0M2QyYTI4MzViMWZmYzI0Nzc1ZWZlMTU5NDIwOTE3NTU0MzYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SEHfsUHqrn2I65OKVD091WFogHA-9oZtzwmTuolTRcI">
> > 
> > 
> > 你的代理可以正常打开ChatGPT的网页么
> 
> 你好，是可以的，也就是说你是正常用的对吧？如果你是正常用的话，我就去找一个国外的服务器试试。

是的 我这边是可以的，不过openai的风控水平时不时有波动，经常需要换har用的并不多hh

**Comment by yayaQAQ** [comment]
> > > > 我按照ninja的文档下载了对应的har文件，docker也走了代理，但是生成失败是为什么呢？ <img alt="image" width="1199" src="https://private-user-images.githubusercontent.com/20497531/297250128-bb8ccb88-d5ba-4455-a80b-20d264753a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjIwMTMsIm5iZiI6MTcwNTQ2MTcxMywicGF0aCI6Ii8yMDQ5NzUzMS8yOTcyNTAxMjgtYmI4Y2NiODgtZDViYS00NDU1LWE4MGItMjBkMjY0NzUzYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMjE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZGI1NTU4N2E0ZWNmNmJkNDU3OTNiNGE0M2QyYTI4MzViMWZmYzI0Nzc1ZWZlMTU5NDIwOTE3NTU0MzYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SEHfsUHqrn2I65OKVD091WFogHA-9oZtzwmTuolTRcI">
> > > 
> > > 
> > > 你的代理可以正常打开ChatGPT的网页么
> > 
> > 
> > 你好，是可以的，也就是说你是正常用的对吧？如果你是正常用的话，我就去找一个国外的服务器试试。
> 
> 是的 我这边是可以的，不过openai的风控水平时不时有波动，经常需要换har用的并不多hh

👌，我再试试，Thanks♪(･ω･)ﾉ

**Comment by yayaQAQ** [comment]
确实还是代理的问题，切到国外就好了。
