### ISSUE TITLE
现在会要求使用captcha验证

### ISSUE THREAD

**Issue by assassinliujie** [Ink-Osier/GenerateArkose#2]
![image](https://github.com/Ink-Osier/GenerateArkose/assets/68693675/b7fbe232-92e1-43d3-835c-44a8f7d4d179)

**Comment by assassinliujie** [comment]
换了个HAR好了，这个项目支持多个HAR文件吗

**Comment by Ink-Osier** [comment]
完全依托于上游的arkose生成项目是否支持，本项目只是在大佬项目的基础上提供了web服务
