### ISSUE TITLE
老哥可否在lts_client那里加上代理

### ISSUE THREAD

**Issue by biek12** [Ink-Osier/GenerateArkose#3]
我没有国外的服务器，只有通过代理上网，老哥可否支持一下代理配置呢？

**Comment by biek12** [comment]
我大概看了一下，应该在funcaptcha.go里面的NewSolver方法中增加一行tls_client.SetProxy()

大致应该是这样，我不太懂Go语言，劳烦老哥

**Comment by Ink-Osier** [comment]
暂时没有加入代理的计划抱歉，建议使用代理的arkose地址，比如closeai.biz，或者如果实在需要代理可以fork一下自己加一下辛苦～
